from __future__ import annotations

import json

from .contracts import ReplayManifest


def build_replay_mjs(manifest: ReplayManifest) -> str:
    """Build a dependency-free Node replay script for the captured kernel request."""
    request_json = json.dumps(manifest.request_body, ensure_ascii=False, indent=2)
    kernel_url = json.dumps(manifest.kernel_url, ensure_ascii=False)
    capture_id = json.dumps(manifest.capture_id, ensure_ascii=False)
    kind = json.dumps(manifest.kind, ensure_ascii=False)
    return f"""// Auto-generated by xiaocai chat replay.
// Usage: node replay.mjs
// Override endpoint: KERNEL_URL=http://127.0.0.1:8000/kernel/run node replay.mjs

const captureId = {capture_id};
const kind = {kind};
const kernelUrl = process.env.KERNEL_URL || {kernel_url};
const requestBody = {request_json};

const response = await fetch(kernelUrl, {{
  method: "POST",
  headers: {{ "content-type": "application/json" }},
  body: JSON.stringify(requestBody),
}});

console.error(`[xiaocai-replay] capture=${{captureId}} kind=${{kind}} status=${{response.status}} url=${{kernelUrl}}`);
console.error(`[xiaocai-replay] session=${{requestBody.session_id || ""}} message=${{requestBody.message || ""}}`);

if (!response.ok) {{
  console.error(await response.text());
  process.exit(1);
}}

const contentType = response.headers.get("content-type") || "";
if (contentType.includes("text/event-stream")) {{
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  while (true) {{
    const {{ value, done }} = await reader.read();
    if (done) break;
    process.stdout.write(decoder.decode(value, {{ stream: true }}));
  }}
}} else {{
  const text = await response.text();
  try {{
    console.log(JSON.stringify(JSON.parse(text), null, 2));
  }} catch {{
    console.log(text);
  }}
}}
"""
