export const XIAOCAI_CHAT_ANTD_THEME = {
  token: {
    borderRadius: 10,
    colorPrimary: '#8b5cf6',
    colorInfo: '#8b5cf6',
    colorLink: '#7c3aed',
  },
} as const

export const XIAOCAI_CHAT_THEME_TOKENS = {
  appBg: '#eef2ff',
  appBorder: '#ddd6fe',
  appShadow: '0 16px 40px rgba(76, 29, 149, 0.10)',
  sidebarBg: '#faf5ff',
  panelBg: '#ffffff',
  divider: '#ddd6fe',
  surfaceBg: '#ffffff',
  surfaceBgActive: '#f5f3ff',
  surfaceBorder: '#ddd6fe',
  surfaceBorderActive: '#8b5cf6',
  textPrimary: '#0f172a',
  textSecondary: '#475569',
  textMuted: '#7c6f9f',
  textInverse: '#ffffff',
  iconNeutral: '#6b5f85',
  iconMuted: '#8b80a8',
  bubbleUserBg: '#8b5cf6',
  bubbleAssistantBg: '#ffffff',
  bubbleAssistantBorder: '#ddd6fe',
  bubbleUserSubtleText: '#f3e8ff',
  composerBg: '#f8f5ff',
  composerBoxBg: '#ffffff',
  inputText: '#0f172a',
  fileTagBg: 'rgba(139, 92, 246, 0.12)',
  fileTagBorder: 'rgba(139, 92, 246, 0.28)',
  fileTagText: '#6d28d9',
  scenarioBg: '#ffffff',
  scenarioCardBg: '#ffffff',
  scenarioCardBgActive: '#f5f3ff',
  scenarioCardBorder: '#ddd6fe',
  scenarioCardBorderActive: '#8b5cf6',
  focusOutline: '0 0 0 3px rgba(139, 92, 246, 0.18)',
} as const
