export const XIAOCAI_CHAT_ANTD_THEME = {
  token: {
    borderRadius: 10,
    colorPrimary: '#2f55ff',
    colorInfo: '#2f55ff',
    colorLink: '#2448f5',
  },
} as const

export const XIAOCAI_CHAT_THEME_TOKENS = {
  appBg: '#ffffff',
  appBorder: '#dbe5ff',
  appShadow: '0 16px 40px rgba(24, 55, 182, 0.10)',
  sidebarBg: '#f7f9ff',
  panelBg: '#ffffff',
  divider: '#dbe5ff',
  surfaceBg: '#ffffff',
  surfaceBgActive: '#f3f6ff',
  surfaceBorder: '#dbe5ff',
  surfaceBorderActive: '#2f55ff',
  textPrimary: '#0f172a',
  textSecondary: '#475569',
  textMuted: '#5c6b94',
  textInverse: '#ffffff',
  iconNeutral: '#4b5c84',
  iconMuted: '#6f7c9c',
  bubbleUserBg: '#2f55ff',
  bubbleAssistantBg: '#ffffff',
  bubbleAssistantBorder: '#dbe5ff',
  bubbleUserSubtleText: '#eef3ff',
  composerBg: '#f8faff',
  composerBoxBg: '#ffffff',
  inputText: '#0f172a',
  fileTagBg: 'rgba(47, 85, 255, 0.12)',
  fileTagBorder: 'rgba(47, 85, 255, 0.28)',
  fileTagText: '#1e40d8',
  scenarioBg: '#ffffff',
  scenarioCardBg: '#ffffff',
  scenarioCardBgActive: '#f3f6ff',
  scenarioCardBorder: '#dbe5ff',
  scenarioCardBorderActive: '#2f55ff',
  focusOutline: '0 0 0 3px rgba(47, 85, 255, 0.18)',
} as const
